# Generated by Django 4.0 on 2022-11-18 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_subcategory_remove_media_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='category_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
            preserve_default=False,
        ),
    ]
