# Generated by Django 4.0 on 2023-01-03 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
    ]
