# Generated by Django 4.0 on 2023-01-03 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
    ]
