# Generated by Django 4.0 on 2023-01-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_rename_user_userinf_alter_orders_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsteller',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
