# Generated by Django 4.0 on 2023-01-08 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_category_image_category_is_homr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_homr',
            new_name='is_home',
        ),
    ]
