# Generated by Django 4.0 on 2023-01-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_rename_is_homr_category_is_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='top_featured',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
