# Generated by Django 4.0 on 2023-01-10 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shop', '0030_remove_cart_total_alter_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinf',
            name='user_id',
            field=models.OneToOneField(default=1001, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
