# Generated by Django 4.0 on 2023-01-10 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_userinf_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinf',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userinf',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userinf',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userinf',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='userinf',
            name='user_name',
        ),
    ]
