# Generated by Django 4.0 on 2023-01-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_alter_shoppingsession_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradress',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='useradress',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='useradress',
            name='province',
        ),
        migrations.AddField(
            model_name='useradress',
            name='address1',
            field=models.CharField(default=1, max_length=1024, verbose_name='Address line 1'),
        ),
        migrations.AddField(
            model_name='useradress',
            name='address2',
            field=models.CharField(default=1, max_length=1024, verbose_name='Address line 2'),
        ),
        migrations.AddField(
            model_name='useradress',
            name='country',
            field=models.CharField(default=1, max_length=3, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='useradress',
            name='name',
            field=models.CharField(default=1, max_length=1024, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='useradress',
            name='zip_code',
            field=models.CharField(default=1, max_length=12, verbose_name='ZIP / Postal code'),
        ),
        migrations.AlterField(
            model_name='useradress',
            name='city',
            field=models.CharField(default=1, max_length=1024, verbose_name='City'),
        ),
    ]
