# Generated by Django 4.0 on 2023-01-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_remove_useradress_adress_remove_useradress_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradress',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Full name'),
        ),
    ]
