# Generated by Django 4.0 on 2023-01-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_alter_useradress_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradress',
            name='address1',
            field=models.CharField(max_length=1024, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='useradress',
            name='address2',
            field=models.CharField(max_length=1024, verbose_name='Address line 2'),
        ),
        migrations.AlterField(
            model_name='useradress',
            name='city',
            field=models.CharField(max_length=1024, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='useradress',
            name='country',
            field=models.CharField(max_length=3, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='useradress',
            name='zip_code',
            field=models.CharField(max_length=12, verbose_name='ZIP / Postal code'),
        ),
    ]
