# Generated by Django 4.0 on 2023-01-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_alter_useradress_address1_alter_useradress_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradress',
            name='country',
            field=models.CharField(max_length=30, verbose_name='Country'),
        ),
    ]
