# Generated by Django 4.0 on 2023-01-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_alter_useradress_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayment',
            name='account_no',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='provider',
        ),
        migrations.AddField(
            model_name='userpayment',
            name='card_no',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='cvv',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='expiration',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='name',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='title',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
