# Generated by Django 4.0 on 2023-01-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_remove_userpayment_account_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='payment_id',
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='card_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='cvv',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='expiration',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
