# Generated by Django 4.0 on 2023-01-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_remove_orders_payment_id_alter_userpayment_card_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
