# Generated by Django 4.0 on 2023-01-29 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_alter_orderitems_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
